default:
  tags:
    - docker

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

variables:
  ALMALINUX9_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/docker-almalinux9-conan:1.2.0"
  CENTOS7_IMAGE: "registry.esss.lu.se/ecdc/ess-dmsc/docker-centos7-conan:1.0.0"
  CONAN_CONFIG_REPO: "http://github.com/ess-dmsc/conan-configuration.git"
  CONAN_USER_HOME: "$CI_PROJECT_DIR/.conan"
  CONAN_REMOTE: "ecdc-conan-virtual"

stages:
  - cppcheck
  - build
  - test
  - publish

cppcheck:
  stage: cppcheck 
  image: $ALMALINUX9_IMAGE
  script:
    - >
      cppcheck \
        --xml \
        --inline-suppr \
        --suppress=unusedFunction \
        --suppress=missingInclude \
        --enable=all \
        --inconclusive \
        --xml-version=2 \
        src/ 2> CppCheckResults.xml
    - pip install --user cppcheck-codequality
    - python3 -m cppcheck_codequality --input-file=CppCheckResults.xml --output-file=CppCheckResults.json
  artifacts:
    reports:
      codequality: CppCheckResults.json
    paths:
      - CppCheckResults.json

build:
  stage: build
  image: $CENTOS7_IMAGE
  cache:
    key: "$CI_COMMIT_SHA-$CONTAINER_IMAGE"
  script:
    - conan install --build missing .
    - conan info conanfile.txt > CONAN_INFO
    - cmake -B build/Release -S . -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
    - cmake --build build/Release
  artifacts:
    paths:
      - .conan
      - build

unit-tests:
  stage: test
  image: $CENTOS7_IMAGE
  dependencies:
    - build
  script:
    - cmake --build build/Release --target unit_tests --target performance_test
    - cd build/Release/
    - ctest
    - ./performance_test/performance_test
    - ./unit_tests/unit_tests --gtest_output=xml:TestResults.xml
    - mv TestResults.xml  $CI_PROJECT_DIR/TestResults.xml
  artifacts:
    reports:
      junit: TestResults.xml
    paths:
      - TestResults.xml

publish:
  stage: publish
  image: $CENTOS7_IMAGE
  dependencies:
    - build
  script:
    - conan config install $CONAN_CONFIG_REPO
    - conan create . ess-dmsc/stable --build=graylog-logger -pr=linux_x86_64_gcc11_legacy
    - conan user $ESS_ARTIFACTORY_ECDC_CONAN_USER --remote=$CONAN_REMOTE --password=$ESS_ARTIFACTORY_ECDC_CONAN_TOKEN
    - conan upload graylog-logger --all -r=$CONAN_REMOTE --confirm
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never
    - if: $CI_COMMIT_TAG
      when: always
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: always
